### ISSUE TITLE
issues installing spdep library R Studio

### ISSUE THREAD

**Issue by mwidener** [utoronto-2i2c/jupyterhub-deploy#26]
Attempted to install spdep package in R. Received following error:

```R
> install.packages("spdep")
Installing package into ‘/home/jovyan/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
also installing the dependencies ‘units’, ‘sf’

trying URL 'https://cran.rstudio.com/src/contrib/units_0.6-7.tar.gz'
Content type 'application/x-gzip' length 957214 bytes (934 KB)
==================================================
downloaded 934 KB

trying URL 'https://cran.rstudio.com/src/contrib/sf_0.9-5.tar.gz'
Content type 'application/x-gzip' length 9001885 bytes (8.6 MB)
==================================================
downloaded 8.6 MB

trying URL 'https://cran.rstudio.com/src/contrib/spdep_1.1-5.tar.gz'
Content type 'application/x-gzip' length 2867051 bytes (2.7 MB)
==================================================
downloaded 2.7 MB

* installing *source* package ‘units’ ...
** package ‘units’ successfully unpacked and MD5 sums checked
** using staged installation
configure: units: 0.6-7
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -std=gnu++11 accepts -g... yes
checking how to run the C++ preprocessor... g++ -std=gnu++11 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdbool.h that conforms to C99... no
checking for _Bool... no
checking for error_at_line... yes
checking for gcc... gcc -std=gnu99
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking for XML_ParserCreate in -lexpat... no
checking udunits2.h usability... no
checking udunits2.h presence... no
checking for udunits2.h... no
checking udunits2/udunits2.h usability... no
checking udunits2/udunits2.h presence... no
checking for udunits2/udunits2.h... no
checking for ut_read_xml in -ludunits2... no
configure: error: in `/tmp/RtmpvDPEs4/R.INSTALL1a715dfcbde0/units':
configure: error: 
--------------------------------------------------------------------------------
  Configuration failed because libudunits2.so was not found. Try installing:
    * deb: libudunits2-dev (Debian, Ubuntu, ...)
    * rpm: udunits2-devel (Fedora, EPEL, ...)
    * brew: udunits (OSX)
  If udunits2 is already installed in a non-standard location, use:
    --configure-args='--with-udunits2-lib=/usr/local/lib'
  if the library was not found, and/or:
    --configure-args='--with-udunits2-include=/usr/include/udunits2'
  if the header was not found, replacing paths with appropriate values.
  You can alternatively set UDUNITS2_INCLUDE and UDUNITS2_LIBS manually.
--------------------------------------------------------------------------------

See `config.log' for more details
ERROR: configuration failed for package ‘units’
* removing ‘/home/jovyan/R/x86_64-pc-linux-gnu-library/4.0/units’
Warning in install.packages :
  installation of package ‘units’ had non-zero exit status
ERROR: dependency ‘units’ is not available for package ‘sf’
* removing ‘/home/jovyan/R/x86_64-pc-linux-gnu-library/4.0/sf’
Warning in install.packages :
  installation of package ‘sf’ had non-zero exit status
ERROR: dependency ‘sf’ is not available for package ‘spdep’
* removing ‘/home/jovyan/R/x86_64-pc-linux-gnu-library/4.0/spdep’
Warning in install.packages :
  installation of package ‘spdep’ had non-zero exit status
```

**Comment by yuvipanda** [comment]
Thank you for being an early tester and spotting it! This should be fixed now - can you confirm?

**Comment by ntaback** [comment]
Thanks @yuvipanda .  I just tried it, but get the following error

> install.packages("spdep")
Installing package into ‘/home/jovyan/R/x86_64-pc-linux-gnu-library/4.0’
(as ‘lib’ is unspecified)
also installing the dependencies ‘units’, ‘sf’

trying URL 'https://cran.rstudio.com/src/contrib/units_0.6-7.tar.gz'
Content type 'application/x-gzip' length 957214 bytes (934 KB)
==================================================
downloaded 934 KB

trying URL 'https://cran.rstudio.com/src/contrib/sf_0.9-5.tar.gz'
Content type 'application/x-gzip' length 9001885 bytes (8.6 MB)
==================================================
downloaded 8.6 MB

trying URL 'https://cran.rstudio.com/src/contrib/spdep_1.1-5.tar.gz'
Content type 'application/x-gzip' length 2867051 bytes (2.7 MB)
==================================================
downloaded 2.7 MB

* installing *source* package ‘units’ ...
** package ‘units’ successfully unpacked and MD5 sums checked
** using staged installation
configure: units: 0.6-7
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -std=gnu++11 accepts -g... yes
checking how to run the C++ preprocessor... g++ -std=gnu++11 -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdbool.h that conforms to C99... no
checking for _Bool... no
checking for error_at_line... yes
checking for gcc... gcc -std=gnu99
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking for XML_ParserCreate in -lexpat... no
checking udunits2.h usability... no
checking udunits2.h presence... no
checking for udunits2.h... no
checking udunits2/udunits2.h usability... no
checking udunits2/udunits2.h presence... no
checking for udunits2/udunits2.h... no
checking for ut_read_xml in -ludunits2... no
configure: error: in `/tmp/RtmpyfaP9p/R.INSTALL947139fe38/units':
configure: error: 
--------------------------------------------------------------------------------
  Configuration failed because libudunits2.so was not found. Try installing:
    * deb: libudunits2-dev (Debian, Ubuntu, ...)
    * rpm: udunits2-devel (Fedora, EPEL, ...)
    * brew: udunits (OSX)
  If udunits2 is already installed in a non-standard location, use:
    --configure-args='--with-udunits2-lib=/usr/local/lib'
  if the library was not found, and/or:
    --configure-args='--with-udunits2-include=/usr/include/udunits2'
  if the header was not found, replacing paths with appropriate values.
  You can alternatively set UDUNITS2_INCLUDE and UDUNITS2_LIBS manually.
--------------------------------------------------------------------------------

See `config.log' for more details
ERROR: configuration failed for package ‘units’
* removing ‘/home/jovyan/R/x86_64-pc-linux-gnu-library/4.0/units’
Warning in install.packages :
  installation of package ‘units’ had non-zero exit status
ERROR: dependency ‘units’ is not available for package ‘sf’
* removing ‘/home/jovyan/R/x86_64-pc-linux-gnu-library/4.0/sf’
Warning in install.packages :
  installation of package ‘sf’ had non-zero exit status
ERROR: dependency ‘sf’ is not available for package ‘spdep’
* removing ‘/home/jovyan/R/x86_64-pc-linux-gnu-library/4.0/spdep’
Warning in install.packages :
  installation of package ‘spdep’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpHA9Y66/downloaded_packages’

**Comment by yuvipanda** [comment]
Thanks for testing, @mwidener. That's very interesting - it works for me but doesn't for you! I'll investigate deeper.

In the meantime, I'll just get spdep installed globally.

**Comment by mwidener** [comment]
Hi all will have time tomorrow to try

—
Michael Widener

**Comment by mwidener** [comment]
Now works for me. Thank you!

**Comment by yuvipanda** [comment]
Thanks for testing, @mwidener!
