### ISSUE TITLE
Nbgrader install?

### ISSUE THREAD

**Issue by hgibling** [utoronto-2i2c/jupyterhub-deploy#99]
Hello,

I'm part of a team developing a new course. We really want to use nbgrader on Jupyterhub to allow for automatic grading of tutorials and assignments, as well as automatic distribution to students. We have heard really good things about nbgrader.

Any chance we could get it installed? Happy to chat more about our ideas.

Thank you,
Heather

**Comment by choldgraf** [comment]
Hey there - sorry for the slow response, some quick thoughts though:

It's actually quite difficult to get nbgrader up and running on cloud infrastructure. We spent a lot of time trying to do this with the Berkeley datahubs, but the challenge is that nbgrader is not very modular, and has strong opinions about the kind of infrastructure on which it runs. This means that it's almost impossible to get it configured right for a cloud setup like JupyterHub on Kubernetes (which is what the U. Toronto deployment uses).

The approach that the Berkeley team took was to work on a cloud-friendly autograder for Jupyter called [Otter Grader](https://otter-grader.readthedocs.io/). Perhaps that would be of interest to you?

I'm going to close this issue because I don't think that we can get this working on the hub, sorry about that!
